version: "3"
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: conquest
    volumes:
      - "/var/lib/pacs-db/db_docker:/var/lib/postgresql/data"
    networks:
      - pacs_network
  orthanc:
    image: osimis/orthanc
    restart: unless-stopped
    networks:
      - pacs_network
    volumes: 
      - "/var/lib/orthanc/db_docker:/var/lib/orthanc/db:Z"
    environment:
      NAME: "My Orthanc"
      DICOM_AET: "MY_ORTHANC"
      DW_ENABLED: "true"
      WVB_ENABLED: "true"
      WVB_ANNOTATIONS_STORAGE_ENABLED: "true"
      DICOM_MODALITIES: |
        {
           "conquest": ["CONQUESTSRV1", "conquest", 5678]
        }
      AUTHZ_WEBSERVICE: http://orthanc-auth-service:8000/
      AUTHZ_TOKEN_HTTP_HEADERS: |
        ["auth-header"]
      AUTHZ_UNCHECKED_RESOURCES: |
        [
                "/osimis-viewer/config.js",
                "/system"
        ]
      AUTHZ_UNCHECKED_FOLDERS: |
        [
              "/plugins",
              "/app/",
              "/wsi/app/",
              "/osimis-viewer/app/",
              "/osimis-viewer/languages/"
        ]
      AUTHZ_UNCHECKED_LEVELS: |
        ["study", "series", "instances", "system"]
  orthanc-auth-service:
    build: pacs-orthanc/node-auth-server
    restart: unless-stopped
    networks:
      - pacs_network
  conquest:
    build:
      context: pacs-conquest/conquest
      args:
        ORTHANC_HOST: orthanc
        ORTHANC_PORT: 4242
    restart: unless-stopped
    depends_on:
      - "db"
    networks:
      - pacs_network
  nginx:
    build: pacs-orthanc/nginx
    depends_on:
      - "orthanc"
    networks:
      - pacs_network
    ports:
      - "443:443"
      - "80:80"
  react-client:
    container_name: react-client
    build:
      context: pacs-client
      args:
        REACT_APP_API_URL: 'https://localhost/admin'
    ports:
      - '3000:80'
    networks:
      - pacs_network
networks:
  pacs_network:
