version: "3"
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: conquest
    ports:
      - "5432:5432"
    volumes:
      - "/var/lib/pacs-db/db_docker:/var/lib/postgresql/data"
    networks:
      - pacs_network
  orthanc:
    image: osimis/orthanc
    restart: unless-stopped
    networks:
      - pacs_network
    ports: 
      - "104:4242"
      - "80:8042"
    volumes: 
      - "/var/lib/orthanc/db_docker:/var/lib/orthanc/db:Z"
    environment:
      NAME: "My Orthanc"
      DICOM_AET: "MY_ORTHANC"
      DW_ENABLED: "true"
      WVB_ENABLED: "true"
      WVB_ANNOTATIONS_STORAGE_ENABLED: "true"
      DICOM_MODALITIES: |
        {
           "conquest": ["CONQUESTSRV1", "conquest", 5678]
        }
  conquest:
    build: conquest
    restart: unless-stopped
    depends_on:
      - "db"
    networks:
      - pacs_network
    ports:
      - "5678:5678"
      - "8080:80"
networks:
  pacs_network:
