version: '3.3'

services:
  react-client:
    container_name: react-client
    build:
      context: .
      args:
        REACT_APP_API_URL: 'https://40.115.0.32/admin'
    ports:
      - '3000:80'
    networks:
      - pacs-network
networks:
  pacs-network:
