version: "3"
services:
  orthanc:
    image: osimis/orthanc
    restart: unless-stopped
    networks:
      - pacs_network
    ports: 
      - "104:4242"
    volumes: 
      - "/var/lib/orthanc/db_docker:/var/lib/orthanc/db:Z"
    environment:
      NAME: "My Orthanc"
      DICOM_AET: "MY_ORTHANC"
      DW_ENABLED: "true"
      WVB_ENABLED: "true"
      WVB_ANNOTATIONS_STORAGE_ENABLED: "true"
      DICOM_MODALITIES: |
        {
           "conquest": ["CONQUESTSRV1", "10.0.0.5", 5678]
        }
  nginx:
    build: nginx
    depends_on:
      - "orthanc"
    networks:
      - pacs_network
    ports:
      - "443:443"
      - "80:80"
networks:
  pacs_network:
