version: "3"
services:
  orthanc:
    image: osimis/orthanc
    restart: unless-stopped
    networks:
      - pacs_network
    ports: 
      - "104:4242"
    volumes: 
      - "/var/lib/orthanc/db_docker:/var/lib/orthanc/db:Z"
    environment:
      NAME: "My Orthanc"
      DICOM_AET: "MY_ORTHANC"
      DW_ENABLED: "true"
      WVB_ENABLED: "true"
      WVB_ANNOTATIONS_STORAGE_ENABLED: "true"
      DICOM_MODALITIES: |
        {
           "conquest": ["CONQUESTSRV1", "conquest_host_or_ip", 5678]
        }
      AUTHZ_WEBSERVICE: http://orthanc-auth-service:8000/
      AUTHZ_TOKEN_HTTP_HEADERS: |
        ["auth-header"]
      AUTHZ_UNCHECKED_RESOURCES: |
        [
                "/osimis-viewer/config.js",
                "/system"
        ]
      AUTHZ_UNCHECKED_FOLDERS: |
        [
              "/plugins",
              "/app/",
              "/wsi/app/",
              "/osimis-viewer/app/",
              "/osimis-viewer/languages/"
        ]
      AUTHZ_UNCHECKED_LEVELS: |
        ["study", "series", "instances", "system"]
  orthanc-auth-service:
    build: node-auth-server
    restart: unless-stopped
    networks:
      - pacs_network
  nginx:
    build: nginx
    depends_on:
      - "orthanc"
    networks:
      - pacs_network
    ports:
      - "443:443"
      - "80:80"
networks:
  pacs_network:
